### ISSUE TITLE
测试一下Issues及Issues的标签是否需要增添和汉化？

### ISSUE THREAD

**Issue by MingxuanXie** [qihuju/qihuju.github.io#1]
<img width="563" alt="image" src="https://user-images.githubusercontent.com/31252716/111737371-77321e80-88ba-11eb-858d-150d137ae315.png">
提示：此处该有图片，若未显示请挂梯子

https://github.com/qihuju/qihuju.github.io/labels

这个是github预设的Issues标签，看看我们需要增减几个？（比如 “brain storm 脑洞？”纯粹用于讨论想法的？）

还有考虑到可能这个项目可能主要是华人参加，是否需要将标签介绍翻译一下方便之后不熟悉github的朋友们也能容易参与？

本Issue assign给了目前所有collaborators，仅为给可能不熟悉github issue功能的朋友做个演示，欢迎随便回复讨论来熟悉这个功能，一周后我会关闭本issue

**Comment by Lupingyue** [comment]
依然有点一脸蒙圈，留个言再说；）

**Comment by qihuju** [comment]
我的建议是标签搞双语吧，比如

bug --> bug/问题
documentation --> documentation/文档
invalid --> invalid/无效

类似这样就可以了，这样墙内外/中英双语人士都能看懂识别

**Comment by askender** [comment]
是否双语可以简单投票决定，我觉得并不是P0优先级的需求，也就是我会投弃权票。
标签的增加应该可以比较开放一些，  我添加一个   brainstorm/脑洞  试试先。

假定奇忽局想做得参与感更强的话， 也许需要设定一些玩法指引？ 比如   issues和disscussion的优先级和功能区分？ 以及是否也利用github的wiki写玩法文档？   或者引流计划？  以及是否可能discord参与的门槛和心理压力更低一点？

**Comment by askender** [comment]
关于定位和参与形式：   https://github.com/qihuju/qihuju.github.io/discussions/5

**Comment by MingxuanXie** [comment]
> 我的建议是标签搞双语吧，比如
> 
> bug --> bug/问题
> documentation --> documentation/文档
> invalid --> invalid/无效
> 
> 类似这样就可以了，这样墙内外/中英双语人士都能看懂识别

嗯 我添加了中文翻译 
不过现在既然添加了专门的discussion页面以后提问这些还是优先写到 discussion页面吧，这边主要留给程序员们😀
